### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by ben-tinc** [AlexandreBrillant/Editix-xml-editor#1]
Hello,

thanks a lot for your software and for making it accessible under GPLv3. I do, however, have a question about your choice of dual-licensing it.

Your wording implies, that the GPL should only be applicable when using your software "non-commercially". The GPL on the other side explicitly allows usage for any purpose and also to redistribute it, as long as I conform to the license (e.g. if I redistribute it, I grant the same rights, publish my changes, etc.).

This is no contradiction, if you understand "non-commercial" simply as "the licensee does not try to sell my software". But I am not sure if this is actually your intention – because sometimes commercial usage is used to mean "usage in any kind of business, even if the software is only used internally as a tool". In the latter case, this would indeed contradict the GPL.

I work in academic research and would like to use your software, so I would be very thankful for a clarification.

Thanks for your time and best regards,
Henning

**Comment by AlexandreBrillant** [comment]
Hello Henning,

Thank you for your feedback. 

You are right the GPL is both for non commercial and commercial usage. I have added in the README.TXT that this is a suggestion because most companies don't like to use the GPL.

I renammed LICENSE-NONCOMMERCIAL.txt to LICENSE-GPL.txt

Best regards,

Alexandre
